config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users/top#index"
  get '/rank/', to: 'users/top#rank'

  get "/admins", to: "admins/top#index", :as => :admins_top

  get "/search", to: "search#index", :as => :search

  resources :recipes do
        resource :favorites, only: [:create, :destroy]
        resources :post_messages, only: [:create, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

end

app/models/post_message.rb
class PostMessage < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :user
    attachment :image

    has_many :post_messages, dependent: :destroy
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    def self.search(search)
      return Recipe.all unless search
      Recipe.where(["title LIKE ?", "%#{search}%"])
    end

    validates :ingredient, presence: true
    validates :title, presence: true
    validates :process, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :sub_recipes, through: :favorites, source: :recipe, dependent: :destroy
  has_many :post_messages, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/admins/top_controller.rb
class Admins::TopController < ApplicationController

	def index
		@recipes = Recipe.all
	end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    case resource
      when User
          root_path
      when Admin
          admins_top_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
      when :user
          root_path
      when :admin
          root_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		recipe = Recipe.find(params[:recipe_id])
		recipe.count += 1
		recipe.save
		favorite = current_user.favorites.build(recipe_id: recipe.id)
		favorite.save
		@recipe = recipe
		@post_message = PostMessage.new
	end

	def destroy
		recipe = Recipe.find(params[:recipe_id])
		recipe.count -= 1
		recipe.save
		favorite = current_user.favorites.find_by(recipe_id: recipe.id)
		favorite.destroy
		@recipe = recipe
		@post_message = PostMessage.new
	end

end

app/controllers/post_messages_controller.rb
class PostMessagesController < ApplicationController

	def create
		recipe = Recipe.find(params[:recipe_id])
		message = current_user.post_messages.new(post_message_params)
		message.recipe_id = recipe.id
		message.save
		@recipe = recipe
		@post_message = PostMessage.new
	end

	def destroy
		message = PostMessage.find_by(id: params[:id])
		message.destroy
		@recipe = Recipe.find(params[:recipe_id])
		@post_message = PostMessage.new
	end

private
	def post_message_params
	  	params.require(:post_message).permit(:message)
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :authenticate_user!, except: [:show, :destroy]

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
		@post_message = PostMessage.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			flash[:notice] = "レシピの更新に成功しました"
			redirect_to recipe_path(@recipe)
		else
			flash[:notice] = "レシピの更新に失敗しました"
			render :edit
		end
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.user_id = current_user.id
		if @recipe.save
			flash[:notice] = "レシピの投稿に成功しました"
			redirect_to recipes_path
		else
			flash[:notice] = "レシピの投稿に失敗しました"
			render :new
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		if user_signed_in?
			redirect_to root_path
		else admin_signed_in?
			redirect_to admins_top_path
		end
	end

	def recipe_params
		params.require(:recipe).permit(:ingredient, :title, :process, :image, :user_id)
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

   def index
   	   @target = params[:target]
   	   if @target == "recipe"
   	   	  @recipes = Recipe.search(params[:search])
   	   end
   end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/top_controller.rb
class Users::TopController < ApplicationController

	def index
	end

	def rank
		@recipes = Recipe.all.order(count: "desc")
	end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_messages_helper.rb
module PostMessagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/top_helper.rb
module Users::TopHelper
end

app/views/favorites/create.js.erb
$('#post_message').html("<%= j(render partial: 'layouts/post_message', locals: {recipe: @recipe, post_message: @post_message }) %>");

app/views/favorites/destroy.js.erb
$('#post_message').html("<%= j(render partial: 'layouts/post_message', locals: {recipe: @recipe, post_message: @post_message }) %>");

app/views/post_messages/create.js.erb
$('#post_message').html("<%= j(render partial: 'layouts/post_message', locals: {recipe: @recipe, post_message: @post_message }) %>");

app/views/post_messages/destroy.js.erb
$('#post_message').html("<%= j(render partial: 'layouts/post_message', locals: {recipe: @recipe, post_message: @post_message }) %>");

app/views/recipes/edit.html.erb
<% if flash[:notice] %>
  <div class = "flash">
  <%= flash[:notice] %>
  </div>
<% end %>


  <h1 class="body2">レシピ編集</h1>
  <br>

<%= form_for @recipe, url: recipe_path(@recipe) do |f| %>

  <%= f.attachment_field :image, placeholder: "画像" %>

    <h2>料理名</h2>
    <%= f.text_field :title %>

    <h2>材料</h2>
    <%= f.text_field :ingredient %>

    <h2>調理手順</h2>
    <%= f.text_area :process %>

    <%= f.submit "変更を保存" %>

<% end %>

</div>

app/views/recipes/index.html.erb
<div class="container">

  <div class="row">
  	<div class="col-md-12">
  	  <div class="text-center">
  	    <h1 class="title3">マイレシピ</h1>
  	  </div>
    </div>
  </div>


  <table class="table">
  	<tbody>
      <% current_user.recipes.each_slice(3) do |recipe3| %>
      <div class="row">
      	<% recipe3.each do |recipe| %>
      	<div class="col-md- text-center">
      	  <td>
      	  	<div class="text-center">
      	  	<%= attachment_image_tag recipe, :image, :fill, 200, 200, class: "", size:'200x200'%><br>
            <%= link_to recipe.title, recipe_path(recipe) %><br>
            <%= recipe.favorites.count %>&nbsp;いいね
            </div>
          </td>
        </div>
        <% end %>
        <tr>
        </tr>
      </div>
      <% end %>
    </tbody>
  </table>

　<div class="row">
    <div class="col-md-12 clearfix">
      <div class="float-right test-box">
      	<button type="button" class="btn btn-success">
          <a class="nav-link text-dark" href="/recipes/new">新規登録</a>
        </button>
      </div>
    </div>
  </div>

app/views/recipes/new.html.erb
<h1>レシピ新規登録</h1>

<% if flash[:notice] %>
  <div class = "flash">
  <%= flash[:notice] %>
  </div>
<% end %>

<%= form_for @recipe, url: recipes_path do |f| %>

  <%= f.attachment_field :image, placeholder: "画像" %>

<h2>料理名</h2>
  <%= f.text_field :title %>

<h2>材料</h2>
  <%= f.text_field :ingredient %>

<h2>調理手順</h2>
  <%= f.text_area :process %>

<%= f.submit "レシピ登録" %>

<% end %>

<%= link_to "MYレシピ一覧", recipes_path %>

app/views/recipes/show.html.erb
<% if flash[:notice] %>
  <div class = "flash">
  <%= flash[:notice] %>
  </div>
<% end %>

<link href="https://fonts.googleapis.com/earlyaccess/nikukyu.css" rel="stylesheet">

<div class="container">

  <div class="row">
  	<div class="col-md-12">
  	  <div class="text-center">
  	    <%= attachment_image_tag @recipe, :image, :fill, 700, 500, class: "", size:'700x500'%>
  	  </div>
    </div>
  </div>
 <br>

  <div class="row">
  	<div class="col-md-12">
  	  <div class="text-center">
  	  	 <h1 class="body2">料理名</h1><h2><%= @recipe.title %></h2><br>
  	  	 <h1 class="body2">材料一覧</h1><h2><%= @recipe.ingredient %></h2><br>
         <h1 class="body2">調理手順</h1><h2><%= @recipe.process %></h2><br>

<div id="post_message">
  <%= render partial: 'layouts/post_message', locals: {recipe: @recipe, post_message: @post_message } %>
</div>

<div class="text-right">
  <% if @recipe.user == current_user %>
    <%= link_to "レシピの編集", edit_recipe_path %>・
    <%= link_to "レシピの削除", recipe_path(@recipe), method: :delete, "data-confirm" => "削除しますか？" %>
  <% elsif admin_signed_in? %>
    <%= link_to "レシピの削除", recipe_path(@recipe), method: :delete, "data-confirm" => "削除しますか？" %>
  <% end %>
</div>