config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users/top#index"
  get '/rank/', to: 'users/top#rank'

  get "/admins", to: "admins/top#index", :as => :admins_top

  get "/search", to: "search#index", :as => :search

  resources :recipes do
        resource :favorites, only: [:create, :destroy]
        resources :post_messages, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :sub_recipes, through: :favorites, source: :recipe, dependent: :destroy
  has_many :post_messages, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/admins/top_controller.rb
class Admins::TopController < ApplicationController

	def index
		@recipes = Recipe.all
	end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/top_controller.rb
class Users::TopController < ApplicationController

	def index
	end

	def rank
		@recipes = Recipe.all.order(count: "desc")
	end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/users/top_helper.rb
module Users::TopHelper
end

app/views/users/top/index.html.erb
<!DOCTYPE html>
<html>
<head>
   <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
   <link href="https://fonts.googleapis.com/earlyaccess/nikukyu.css" rel="stylesheet">
</head>

<body>
<div class="container">

  <div class="row">
    <div class ="col-md-12">
  	  <div class="text-center">
  	    <h1 class="title2">ずぼらめし</h1	>
  	  </div>
    </div>
  </div>

  <div class="row">
    <div class ="col-md-12">
  	  <div class="text-center">
  	    <h2 class="body"><br>それは、究極を極めし飯のこと</h2>
  	  </div>
  	</div>
  </div>

  <div class="row">
    <div class ="col-md-12">
  	  <div class="text-center">
  	    <h2 class="body"><br>ここは、究極の飯を共有する場所</h2>
  	  </div>
  	</div>
  </div>

  <div class="row">
    <div class ="col-md-12">
  	  <div class="text-center">
  	    <h2 class="body"><br>自分だけのずぼら飯を見つけ出そう</h2>
  	  </div>
  	</div>
  </div>

  <div class="row">
    <div class="col-md-12 clearfix">
      <%= link_to rank_path do %>
      <div class="float-right test-box"><br><%= image_tag('usa.png') %></div>
      <% end %>
    </div>
  </div>

</div>

app/views/users/top/rank.html.erb
<div class="container">

  <div class="row">
  	<div class="col-md-12">
  	  <div class="text-center">
  	    <h1 class="title3">レシピランキング</h1>
  	  </div>
    </div>
  </div>


  <table class="table">
  	<tbody>
      <% @recipes.each_slice(3) do |recipe3| %>
      <div class="row">
      	<% recipe3.each do |recipe| %>
      	<div class="col-md- text-center">
      	  <td>
      	  	<div class="text-center">
      	  	<%= attachment_image_tag recipe, :image, :fill, 200, 200, class: "", size:'200x200'%><br>
            <%= link_to recipe.title, recipe_path(recipe) %><br>
            <%= recipe.favorites.count %>&nbsp;いいね
            </div>
          </td>
        </div>
        <% end %>
        <tr>
        </tr>
      </div>
      <% end %>
    </tbody>
  </table>