config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "users/top#index"
  get '/rank/', to: 'users/top#rank'

  get "/admins", to: "admins/top#index", :as => :admins_top

  get "/search", to: "search#index", :as => :search

  resources :recipes do
        resource :favorites, only: [:create, :destroy]
        resources :post_messages, only: [:create, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

end

app/models/post_message.rb
class PostMessage < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ApplicationRecord

	belongs_to :user
    attachment :image

    has_many :post_messages, dependent: :destroy
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
    end

    def self.search(search)
      return Recipe.all unless search
      Recipe.where(["title LIKE ?", "%#{search}%"])
    end

    validates :ingredient, presence: true
    validates :title, presence: true
    validates :process, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :sub_recipes, through: :favorites, source: :recipe, dependent: :destroy
  has_many :post_messages, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/admins/top_controller.rb
class Admins::TopController < ApplicationController

	def index
		@recipes = Recipe.all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    case resource
      when User
          root_path
      when Admin
          admins_top_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
      when :user
          root_path
      when :admin
          root_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		recipe = Recipe.find(params[:recipe_id])
		recipe.count += 1
		recipe.save
		favorite = current_user.favorites.build(recipe_id: recipe.id)
		favorite.save
		@recipe = recipe
		@post_message = PostMessage.new
	end

	def destroy
		recipe = Recipe.find(params[:recipe_id])
		recipe.count -= 1
		recipe.save
		favorite = current_user.favorites.find_by(recipe_id: recipe.id)
		favorite.destroy
		@recipe = recipe
		@post_message = PostMessage.new
	end

end

app/controllers/post_messages_controller.rb
class PostMessagesController < ApplicationController

	def create
		recipe = Recipe.find(params[:recipe_id])
		message = current_user.post_messages.new(post_message_params)
		message.recipe_id = recipe.id
		message.save
		@recipe = recipe
		@post_message = PostMessage.new
	end

	def destroy
		message = PostMessage.find_by(id: params[:id])
		message.destroy
		@recipe = Recipe.find(params[:recipe_id])
		@post_message = PostMessage.new
	end

private
	def post_message_params
	  	params.require(:post_message).permit(:message)
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :authenticate_user!, except: [:show, :destroy]

	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
		@post_message = PostMessage.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			flash[:notice] = "レシピの更新に成功しました"
			redirect_to recipe_path(@recipe)
		else
			flash[:notice] = "レシピの更新に失敗しました"
			render :edit
		end
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.user_id = current_user.id
		if @recipe.save
			flash[:notice] = "レシピの投稿に成功しました"
			redirect_to recipes_path
		else
			flash[:notice] = "レシピの投稿に失敗しました"
			render :new
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		if user_signed_in?
			redirect_to root_path
		else admin_signed_in?
			redirect_to admins_top_path
		end
	end

	def recipe_params
		params.require(:recipe).permit(:ingredient, :title, :process, :image, :user_id)
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

   def index
   	   @target = params[:target]
   	   if @target == "recipe"
   	   	  @recipes = Recipe.search(params[:search])
   	   end
   end

end

app/controllers/users/top_controller.rb
class Users::TopController < ApplicationController

	def index
	end

	def rank
		@recipes = Recipe.all.order(count: "desc")
	end

end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_messages_helper.rb
module PostMessagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/top_helper.rb
module Users::TopHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_post_message.html.erb
<div class="text-right">
<% if user_signed_in? %>

 <% if recipe.favorited_by?(current_user) %>
   <%= link_to recipe_favorites_path(recipe), method: :delete , remote: true do %>
   <%= recipe.favorites.count %> お気に入り
   <% end %>

 <% else %>
   <%= link_to recipe_favorites_path(recipe), method: :post, remote: true do %>
   <%= recipe.favorites.count %> お気に入り
   <% end %>
 <% end %>
<% end %><br><br>
</div>

   <div class="row">
    <div class="col-md-12">
      <div class="text-center">

   <% recipe.post_messages.each do |post_message| %>
   <%= post_message.message %>
   <%= post_message.user.name %>

   <% if post_message.user == current_user %>
     <%= link_to "削除", recipe_post_message_path(recipe.id, post_message.id), method: :delete, remote: true  %>
   <% end %>

   <% end %>
      </div>
     </div>
   </div>

   <div class="row">
    <div class="col-md-12">

   <div class="text-center">
   <% if user_signed_in? %><br>
     <%= form_for [recipe, post_message], remote: true do |f| %>
     <%= f.text_area :message %>
     <%= f.submit "送信する" %>
      <% end %>
   <% end %>
   </div>
</td>
    </div>
　　</div>


<% if user_signed_in? == false %>
  <h2><%= link_to "レシピ一覧", root_path %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zuborasann</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/earlyaccess/nikukyu.css" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-dark" style="background-color:#AEFFBD;">
    <a class="navbar-brand" style="color:#000000;" href="/"><h1 class = "title">ずぼらさん</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>

        <li class="nav-item">
          <a class="nav-link text-dark" href="/rank"><br>人気レシピ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" href="/recipes">マイレシピ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark" data-method="delete" href="/users/sign_out">ログアウト
          </a>
        </li>
      </ul>

    <%= form_tag(search_path,:method => 'get',class:'navbar-form') do %>
    <%= text_field_tag :search, nil, :placeholder => '検索' %>
    <%= hidden_field_tag :target, 'recipe' %>
    <%= submit_tag '検索', :title => nil %>
    <% end %>
    </div>
  </nav>

<% else %>
 　　　<% if admin_signed_in? %>

        <a class="nav-link text-dark" data-method="delete" href="/admins/sign_out">ログアウト
        </a>
    　</ul>

    <%= form_tag(search_path,:method => 'get',class:'navbar-form') do %>
    <%= text_field_tag :search, nil, :placeholder => '検索' %>
    <%= hidden_field_tag :target, 'recipe' %>
    <%= submit_tag '検索', :title => nil %>
    <% end %>
  </div>
</nav>

<% else %>

    　<li class="nav nav-item">
        <a class="nav-link text-dark" href="/rank">人気レシピ</a>
      </li>
      <li class="nav nav-item">
        <a class="nav-link text-dark" data-method="post" href="/users/sign_in">ログイン</a>
      </li>
      <li class="nav nav-item">
        <a class="nav-link text-dark"　data-method="delete" href="/admins/sign_in">Admin
        </a>
      </li>
    </ul>

    <%= form_tag(search_path,:method => 'get',class:'navbar-form') do %>
    <%= text_field_tag :search, nil, :placeholder => '検索' %>
    <%= hidden_field_tag :target, 'recipe' %>
    <%= submit_tag '検索', :title => nil %>
    <% end %>
  </div>
</nav>

    <% end %>
    <% end %>
<%= yield %>
</body>
</html>